export const PROJECTS = [
  {
    title: "eCommerce",
    description: "Simulacion de eCommerce para poder realizar tus pedidos y compras de las distintas categorias de productos con las que contamos.",
    technologies: ["React", "JS", "HTML", "CSS"],
    github: "https://github.com/SoyRandy708/eCommerce",
    web: "https://proyect-eccomerce.netlify.app/",
    image: "",
  },
  {
    title: "ToDo List",
    description: "Sitio web para poder crear, modificar, eliminar y guardar tus tareas que tienes pendientes, con la opcion de poder filtrarlos por progreso, o por su nombre.",
    technologies: ["React", "Sass"],
    github: "https://github.com/SoyRandy708/ToDo-List",
    web: "https://soyrandy708.github.io/ToDo-List/", 
    image: "",
  },
  {
    title: "Formulario con Validaciones",
    description: "Formulario sencillo en el que se hacen validaciones para saber si se estan ingresando correctamente los datos de que se piden.",
    technologies: ["HTML", "CSS", "JS"],
    github: "https://github.com/SoyRandy708/FormularioConValidaciones",
    web: "https://soyrandy708.github.io/FormularioConValidaciones/",
    image: "",
  },
  {
    title: "Calculadora",
    description: "Calculadora basica para poder realizar distintas operacion como suma, resta, multiplicacion y division.",
    technologies: ["HTML", "CSS", "JS"],
    github: "https://github.com/SoyRandy708/Calculadora-JS",
    web: "https://soyrandy708.github.io/Calculadora-JS/",
    image: "",
  },
  {
    title: "Numeros Aleatorios",
    description: "Generador de numeros aleatorios donde puedes ingresar el rango entre los cuales se daran los resultados y la cantidad de resultado que quieres.",
    technologies: ["HTML", "CSS", "JS"],
    github: "https://github.com/SoyRandy708/NumerosAleatorios",
    web: "https://soyrandy708.github.io/NumerosAleatorios/",
    image: "",
  },
  // {
  //   title: "",
  //   description: "",
  //   technologies: [""],
  //   github: "",
  //   web: "",
  //   image: "",
  // },
]